### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by kenjis**
~~Because I may not remember how to update QA tools.~~
Minor fixes.

### CODE REVIEW

**Comment by koriym** [comment]
We do not need to know that?
`Composer update` update QATool as well.

See composer.json.
```
        "post-install-cmd": "@composer bin all install --ansi",
        "post-update-cmd": "@composer bin all update --ansi"
```

**Comment by kenjis** [comment]
I didn't see it. You're right.

**Comment by kenjis** [comment]
@koriym I removed about `composer bin all update`.
Check, please.

**Comment by koriym** [comment]
@kenjis Thanks as always.

**Pull request merged**
