### PR TITLE
Add phploc and phpmetrics

### PR DESCRIPTION
**Pull request by kenjis**
I always use phploc and phpmetrics.
So I hope new PHP projects have them.

### CODE REVIEW

**Comment by koriym** [comment]
Feel free to do PR in `bear/qatools` as well.
https://github.com/bearsunday/BEAR.QATools

I exclude `phploc` from skeleton because it is like more for CI tools? (like document generator)
or you may need those tools at development. Thoughts?

**Comment by kenjis** [comment]
I sent PR: https://github.com/bearsunday/BEAR.QATools/pull/9

> I exclude phploc from skeleton because it is like more for CI tools? (like document generator)
or you may need those tools at development. Thoughts?

I see code size (LOC or xLOC) at development. 
But yeah, it is also QA tool and is like more for CI tools.

**Comment by koriym** [comment]
Thank you for the PR. Merged.

**Comment by koriym** [comment]
About LOC, still not sure ... 🤔

**Comment by koriym** [comment]
@kenjis I close this issue, feel free to reopen when you need.

**Pull request closed without merging**
