### PR TITLE
updated readme for composer1.x user

### LINKED ISSUE #55: create-project hangs up at postInstall process with composer 1.x (php-skeleton v1.1.6)
my php versions are 7.3.11, 7.4.7. both effected.

output is below:
```
***@quartet92 projects % composer create-project koriym/php-skeleton myproject
Creating a "koriym/php-skeleton" project at "./myproject"
Installing koriym/php-skeleton (1.1.6)
  - Installing koriym/php-skeleton (1.1.6): Loading from cache
Created project in /path/to/projects/myproject
> Koriym\PhpSkeleton\Installer::preInstall

What is the vendor name?
(MyVendor): Quartetcom

What is the package name?
(MyPackage): Quartetcom

MyPackage

What is your name?
(77web): 
77web

What is your email address ?
(****@quartetcom.co.jp): 
****@quartetcom.co.jp
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 74 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.11.99): Loading from cache
  - Installing squizlabs/php_codesniffer (3.5.8): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.7.0): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/type (1.1.3): Loading from cache
  - Installing sebastian/resource-operations (2.0.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (3.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.2): Loading from cache
  - Installing sebastian/environment (4.2.3): Loading from cache
  - Installing sebastian/diff (3.0.2): Loading from cache
  - Installing sebastian/comparator (3.0.2): Loading from cache
  - Installing phpunit/php-timer (2.1.2): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (2.0.2): Loading from cache
  - Installing theseer/tokenizer (1.2.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (3.1.1): Loading from cache
  - Installing phpunit/php-code-coverage (7.0.10): Loading from cache
  - Installing doctrine/instantiator (1.3.1): Loading from cache
  - Installing phpdocumentor/reflection-common (2.2.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.20.0): Loading from cache
  - Installing webmozart/assert (1.9.1): Loading from cache
  - Installing phpdocumentor/type-resolver (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (5.2.2): Loading from cache
  - Installing phpspec/prophecy (1.12.1): Loading from cache
  - Installing phar-io/version (2.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.3): Loading from cache
  - Installing myclabs/deep-copy (1.10.1): Loading from cache
  - Installing phpunit/phpunit (8.5.8): Loading from cache
  - Installing psr/log (1.1.3): Loading from cache
  - Installing composer/xdebug-handler (1.4.4): Loading from cache
  - Installing symfony/polyfill-php80 (v1.20.0): Loading from cache
  - Installing symfony/filesystem (v5.1.8): Loading from cache
  - Installing symfony/deprecation-contracts (v2.2.0): Loading from cache
  - Installing symfony/config (v5.1.8): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/service-contracts (v2.2.0): Loading from cache
  - Installing symfony/dependency-injection (v5.1.8): Loading from cache
  - Installing pdepend/pdepend (2.8.0): Loading from cache
  - Installing phpmd/phpmd (2.9.1): Loading from cache
  - Installing phpstan/phpstan (0.12.54): Loading from cache
  - Installing webmozart/path-util (2.3.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.20.0): Loading from cache
  - Installing symfony/polyfill-intl-normalizer (v1.20.0): Loading from cache
  - Installing symfony/polyfill-intl-grapheme (v1.20.0): Loading from cache
  - Installing symfony/string (v5.1.8): Loading from cache
  - Installing symfony/polyfill-php73 (v1.20.0): Loading from cache
  - Installing symfony/console (v5.1.8): Loading from cache
  - Installing openlss/lib-array2xml (1.0.0): Loading from cache
  - Installing nikic/php-parser (v4.10.2): Loading from cache
  - Installing netresearch/jsonmapper (v2.1.0): Loading from cache
  - Installing felixfbecker/language-server-protocol (v1.5.0): Loading from cache
  - Installing felixfbecker/advanced-json-rpc (v3.1.1): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Loading from cache
  - Installing composer/semver (3.2.2): Loading from cache
  - Installing amphp/amp (v2.5.1): Loading from cache
  - Installing amphp/byte-stream (v1.8.0): Loading from cache
  - Installing vimeo/psalm (4.1.1): Loading from cache
  - Installing phpmetrics/phpmetrics (v2.7.4): Loading from cache
  - Installing phpstan/phpdoc-parser (0.4.9): Loading from cache
  - Installing slevomat/coding-standard (6.4.1): Loading from cache
  - Installing doctrine/coding-standard (8.2.0): Loading from cache
  - Installing react/promise (v2.8.0): Loading from cache
  - Installing symfony/process (v5.1.8): Loading from cache
  - Installing symfony/finder (v5.1.8): Loading from cache
  - Installing seld/phar-utils (1.1.1): Loading from cache
  - Installing seld/jsonlint (1.8.2): Loading from cache
  - Installing justinrainbow/json-schema (5.2.10): Loading from cache
  - Installing composer/spdx-licenses (1.5.4): Loading from cache
  - Installing composer/ca-bundle (1.2.8): Loading from cache
  - Installing composer/composer (2.0.6): Loading from cache
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.7.2)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0.0)
phpunit/phpunit suggests installing ext-xdebug (*)
symfony/config suggests installing symfony/yaml (To use the yaml reference dumper)
symfony/dependency-injection suggests installing symfony/yaml
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/console suggests installing symfony/event-dispatcher
symfony/console suggests installing symfony/lock
vimeo/psalm suggests installing ext-igbinary (^2.0.5)
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
31 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../doctrine/coding-standard/lib,../../slevomat/coding-standard
> Koriym\PhpSkeleton\Installer::postInstall

```

### PR DESCRIPTION
**Pull request by 77web**
close #55

### CODE REVIEW

**Comment by koriym** [comment]
We should fix the code not the document? But yes, until then it would be great for the user have the problem. 

"現在の最新バージョンでは問題のある場合があり、うまくいかない場合は" とか注釈を入れましょうか？

**Comment by 77web** [comment]
@koriym 

I understand composer1.x is outdated today. so we don't have to fix code, I suppose. 🤔 
we should focus on new composer2 features instead :sparkles:

> 注釈

okay, I'll do it at my lunch break today :smile:

**Comment by kenjis** [comment]
@koriym 

You also have the warning with Composer 1.x: 
> PHP Warning:  include(/private/tmp/a/vendor/composer/../composer/InstalledVersions.php): failed to open stream: No such file or directory in /private/tmp/a/vendor/composer/ClassLoader.php on line 444
https://github.com/koriym/Koriym.PhpSkeleton/issues/55#issuecomment-724674839

The warning comes from psalm. Does psalm need Composer 2.0?

**Comment by koriym** [comment]
> The warning comes from psalm. Does psalm need Composer 2.0?

I don't think so.
But same Warning in "ClassLoader.php on line 444".

```
 % composer create-project koriym/php-skeleton a
Creating a "koriym/php-skeleton" project at "./a"
Installing koriym/php-skeleton (1.1.6)
  - Installing koriym/php-skeleton (1.1.6): Downloading (100%)         
Created project in /private/tmp/a
> Koriym\PhpSkeleton\Installer::preInstall

What is the vendor name?
(MyVendor): 
MyVendor

What is the package name?
(MyPackage): 
MyPackage

What is your name?
(Akihito Koriyama): 
Akihito Koriyama

What is your email address ?
(akihito.koriyama@gmail.com): 
akihito.koriyama@gmail.com
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 74 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.11.99.1): Downloading (100%)         
  - Installing squizlabs/php_codesniffer (3.5.8): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.7.0): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/type (1.1.3): Loading from cache
  - Installing sebastian/resource-operations (2.0.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (3.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.2): Loading from cache
  - Installing sebastian/environment (4.2.3): Loading from cache
  - Installing sebastian/diff (3.0.2): Loading from cache
  - Installing sebastian/comparator (3.0.2): Loading from cache
  - Installing phpunit/php-timer (2.1.2): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (2.0.2): Loading from cache
  - Installing theseer/tokenizer (1.2.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (3.1.1): Loading from cache
  - Installing phpunit/php-code-coverage (7.0.10): Loading from cache
  - Installing doctrine/instantiator (1.4.0): Downloading (100%)         
  - Installing phpdocumentor/reflection-common (2.2.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.20.0): Loading from cache
  - Installing webmozart/assert (1.9.1): Loading from cache
  - Installing phpdocumentor/type-resolver (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (5.2.2): Loading from cache
  - Installing phpspec/prophecy (1.12.1): Loading from cache
  - Installing phar-io/version (2.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.3): Loading from cache
  - Installing myclabs/deep-copy (1.10.1): Loading from cache
  - Installing phpunit/phpunit (8.5.9): Downloading (100%)         
  - Installing psr/log (1.1.3): Loading from cache
  - Installing composer/xdebug-handler (1.4.4): Loading from cache
  - Installing symfony/polyfill-php80 (v1.20.0): Loading from cache
  - Installing symfony/filesystem (v5.1.8): Loading from cache
  - Installing symfony/deprecation-contracts (v2.2.0): Loading from cache
  - Installing symfony/config (v5.1.8): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/service-contracts (v2.2.0): Loading from cache
  - Installing symfony/dependency-injection (v5.1.8): Loading from cache
  - Installing pdepend/pdepend (2.8.0): Loading from cache
  - Installing phpmd/phpmd (2.9.1): Loading from cache
  - Installing phpstan/phpstan (0.12.54): Downloading (100%)         
  - Installing webmozart/path-util (2.3.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.20.0): Loading from cache
  - Installing symfony/polyfill-intl-normalizer (v1.20.0): Loading from cache
  - Installing symfony/polyfill-intl-grapheme (v1.20.0): Loading from cache
  - Installing symfony/string (v5.1.8): Loading from cache
  - Installing symfony/polyfill-php73 (v1.20.0): Loading from cache
  - Installing symfony/console (v5.1.8): Loading from cache
  - Installing openlss/lib-array2xml (1.0.0): Loading from cache
  - Installing nikic/php-parser (v4.10.2): Loading from cache
  - Installing netresearch/jsonmapper (v2.1.0): Loading from cache
  - Installing felixfbecker/language-server-protocol (v1.5.0): Loading from cache
  - Installing felixfbecker/advanced-json-rpc (v3.1.1): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Loading from cache
  - Installing composer/semver (3.2.2): Loading from cache
  - Installing amphp/amp (v2.5.1): Downloading (100%)         
  - Installing amphp/byte-stream (v1.8.0): Loading from cache
  - Installing vimeo/psalm (4.1.1): Loading from cache
  - Installing phpmetrics/phpmetrics (v2.7.4): Loading from cache
  - Installing phpstan/phpdoc-parser (0.4.9): Loading from cache
  - Installing slevomat/coding-standard (6.4.1): Loading from cache
  - Installing doctrine/coding-standard (8.2.0): Loading from cache
  - Installing react/promise (v2.8.0): Loading from cache
  - Installing symfony/process (v5.1.8): Loading from cache
  - Installing symfony/finder (v5.1.8): Loading from cache
  - Installing seld/phar-utils (1.1.1): Loading from cache
  - Installing seld/jsonlint (1.8.3): Downloading (100%)         
  - Installing justinrainbow/json-schema (5.2.10): Loading from cache
  - Installing composer/spdx-licenses (1.5.4): Loading from cache
  - Installing composer/ca-bundle (1.2.8): Loading from cache
  - Installing composer/composer (2.0.6): Downloading (100%)         
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.7.2)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0.0)
phpunit/phpunit suggests installing ext-xdebug (*)
symfony/config suggests installing symfony/yaml (To use the yaml reference dumper)
symfony/dependency-injection suggests installing symfony/yaml
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/console suggests installing symfony/event-dispatcher
symfony/console suggests installing symfony/lock
vimeo/psalm suggests installing ext-igbinary (^2.0.5)
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
31 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../doctrine/coding-standard/lib,../../slevomat/coding-standard
> Koriym\PhpSkeleton\Installer::postInstall
PHP Warning:  include(/private/tmp/a/vendor/composer/../composer/InstalledVersions.php): failed to open stream: No such file or directory in /private/tmp/a/vendor/composer/ClassLoader.php on line 444
Warning: include(/private/tmp/a/vendor/composer/../composer/InstalledVersions.php): failed to open stream: No such file or directory in /private/tmp/a/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/private/tmp/a/vendor/composer/../composer/InstalledVersions.php' for inclusion (include_path='.:/usr/local/Cellar/php/7.4.12/share/php/pear') in /private/tmp/a/vendor/composer/ClassLoader.php on line 444
Warning: include(): Failed opening '/private/tmp/a/vendor/composer/../composer/InstalledVersions.php' for inclusion (include_path='.:/usr/local/Cellar/php/7.4.12/share/php/pear') in /private/tmp/a/vendor/composer/ClassLoader.php on line 444
Scanning files...
Analyzing files...

░░░
my-vendor/my-package package created.
Happy quality coding!
```

**Comment by koriym** [comment]
Merged. But hope we will find the real cause and revert this PR!
@77web @kenjis

**Pull request merged**
