### PR TITLE
Fix installation error

### LINKED ISSUE #61: Script Koriym\PhpSkeleton\Installer::postInstall handling the post-create-project-cmd event terminated with an exception
Can't create a project.

```
$ composer create-project koriym/php-skeleton test
Creating a "koriym/php-skeleton" project at "./test"
Installing koriym/php-skeleton (1.1.7)
  - Installing koriym/php-skeleton (1.1.7): Extracting archive
Created project in /Users/kenji/tmp/test
> Koriym\PhpSkeleton\Installer::preInstall

What is the vendor name?
(MyVendor): Kenjis
Kenjis

What is the package name?
(MyPackage): AwesomePackage
AwesomePackage

What is your name?
(kenjis): 
kenjis

What is your email address ?
(kenji.uui@gmail.com): 
kenji.uui@gmail.com
Loading composer repositories with package information
Updating dependencies
Lock file operations: 74 installs, 0 updates, 0 removals
  - Locking amphp/amp (v2.5.1)
  - Locking amphp/byte-stream (v1.8.0)
  - Locking composer/ca-bundle (1.2.8)
  - Locking composer/composer (2.0.8)
  - Locking composer/package-versions-deprecated (1.11.99.1)
  - Locking composer/semver (3.2.4)
  - Locking composer/spdx-licenses (1.5.5)
  - Locking composer/xdebug-handler (1.4.5)
  - Locking dealerdirect/phpcodesniffer-composer-installer (v0.7.1)
  - Locking dnoegel/php-xdg-base-dir (v0.1.1)
  - Locking doctrine/coding-standard (8.2.0)
  - Locking doctrine/instantiator (1.4.0)
  - Locking felixfbecker/advanced-json-rpc (v3.1.1)
  - Locking felixfbecker/language-server-protocol (v1.5.0)
  - Locking justinrainbow/json-schema (5.2.10)
  - Locking myclabs/deep-copy (1.10.2)
  - Locking netresearch/jsonmapper (v2.1.0)
  - Locking nikic/php-parser (v4.10.4)
  - Locking openlss/lib-array2xml (1.0.0)
  - Locking pdepend/pdepend (2.8.0)
  - Locking phar-io/manifest (2.0.1)
  - Locking phar-io/version (3.0.4)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.2.2)
  - Locking phpdocumentor/type-resolver (1.4.0)
  - Locking phpmd/phpmd (2.9.1)
  - Locking phpmetrics/phpmetrics (v2.7.4)
  - Locking phpspec/prophecy (1.12.2)
  - Locking phpstan/phpdoc-parser (0.4.9)
  - Locking phpstan/phpstan (0.12.64)
  - Locking phpunit/php-code-coverage (7.0.14)
  - Locking phpunit/php-file-iterator (2.0.3)
  - Locking phpunit/php-text-template (1.2.1)
  - Locking phpunit/php-timer (2.1.3)
  - Locking phpunit/php-token-stream (4.0.4)
  - Locking phpunit/phpunit (8.5.13)
  - Locking psr/container (1.0.0)
  - Locking psr/log (1.1.3)
  - Locking react/promise (v2.8.0)
  - Locking sebastian/code-unit-reverse-lookup (1.0.2)
  - Locking sebastian/comparator (3.0.3)
  - Locking sebastian/diff (3.0.3)
  - Locking sebastian/environment (4.2.4)
  - Locking sebastian/exporter (3.1.3)
  - Locking sebastian/global-state (3.0.1)
  - Locking sebastian/object-enumerator (3.0.4)
  - Locking sebastian/object-reflector (1.1.2)
  - Locking sebastian/recursion-context (3.0.1)
  - Locking sebastian/resource-operations (2.0.2)
  - Locking sebastian/type (1.1.4)
  - Locking sebastian/version (2.0.1)
  - Locking seld/jsonlint (1.8.3)
  - Locking seld/phar-utils (1.1.1)
  - Locking slevomat/coding-standard (6.4.1)
  - Locking squizlabs/php_codesniffer (3.5.8)
  - Locking symfony/config (v5.2.1)
  - Locking symfony/console (v5.2.1)
  - Locking symfony/dependency-injection (v5.2.1)
  - Locking symfony/deprecation-contracts (v2.2.0)
  - Locking symfony/filesystem (v5.2.1)
  - Locking symfony/finder (v5.2.1)
  - Locking symfony/polyfill-ctype (v1.20.0)
  - Locking symfony/polyfill-intl-grapheme (v1.20.0)
  - Locking symfony/polyfill-intl-normalizer (v1.20.0)
  - Locking symfony/polyfill-mbstring (v1.20.0)
  - Locking symfony/polyfill-php73 (v1.20.0)
  - Locking symfony/polyfill-php80 (v1.20.0)
  - Locking symfony/process (v5.2.1)
  - Locking symfony/service-contracts (v2.2.0)
  - Locking symfony/string (v5.2.1)
  - Locking theseer/tokenizer (1.2.0)
  - Locking vimeo/psalm (4.3.2)
  - Locking webmozart/assert (1.9.1)
  - Locking webmozart/path-util (2.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 74 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.11.99.1): Extracting archive
  - Installing squizlabs/php_codesniffer (3.5.8): Extracting archive
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.7.1): Extracting archive
  - Installing symfony/polyfill-php80 (v1.20.0): Extracting archive
  - Installing symfony/process (v5.2.1): Extracting archive
  - Installing symfony/finder (v5.2.1): Extracting archive
  - Installing symfony/polyfill-ctype (v1.20.0): Extracting archive
  - Installing symfony/filesystem (v5.2.1): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.20.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.20.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.20.0): Extracting archive
  - Installing symfony/string (v5.2.1): Extracting archive
  - Installing psr/container (1.0.0): Extracting archive
  - Installing symfony/service-contracts (v2.2.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.20.0): Extracting archive
  - Installing symfony/console (v5.2.1): Extracting archive
  - Installing seld/phar-utils (1.1.1): Extracting archive
  - Installing seld/jsonlint (1.8.3): Extracting archive
  - Installing react/promise (v2.8.0): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing justinrainbow/json-schema (5.2.10): Extracting archive
  - Installing composer/xdebug-handler (1.4.5): Extracting archive
  - Installing composer/spdx-licenses (1.5.5): Extracting archive
  - Installing composer/semver (3.2.4): Extracting archive
  - Installing composer/ca-bundle (1.2.8): Extracting archive
  - Installing composer/composer (2.0.8): Extracting archive
  - Installing phpstan/phpdoc-parser (0.4.9): Extracting archive
  - Installing slevomat/coding-standard (6.4.1): Extracting archive
  - Installing doctrine/coding-standard (8.2.0): Extracting archive
  - Installing webmozart/assert (1.9.1): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.4.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.2.2): Extracting archive
  - Installing symfony/deprecation-contracts (v2.2.0): Extracting archive
  - Installing symfony/dependency-injection (v5.2.1): Extracting archive
  - Installing symfony/config (v5.2.1): Extracting archive
  - Installing pdepend/pdepend (2.8.0): Extracting archive
  - Installing phpmd/phpmd (2.9.1): Extracting archive
  - Installing nikic/php-parser (v4.10.4): Extracting archive
  - Installing phpmetrics/phpmetrics (v2.7.4): Extracting archive
  - Installing phpstan/phpstan (0.12.64): Extracting archive
  - Installing phpunit/php-token-stream (4.0.4): Extracting archive
  - Installing sebastian/version (2.0.1): Extracting archive
  - Installing sebastian/type (1.1.4): Extracting archive
  - Installing sebastian/resource-operations (2.0.2): Extracting archive
  - Installing sebastian/recursion-context (3.0.1): Extracting archive
  - Installing sebastian/object-reflector (1.1.2): Extracting archive
  - Installing sebastian/object-enumerator (3.0.4): Extracting archive
  - Installing sebastian/global-state (3.0.1): Extracting archive
  - Installing sebastian/exporter (3.1.3): Extracting archive
  - Installing sebastian/environment (4.2.4): Extracting archive
  - Installing sebastian/diff (3.0.3): Extracting archive
  - Installing sebastian/comparator (3.0.3): Extracting archive
  - Installing phpunit/php-timer (2.1.3): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing phpunit/php-file-iterator (2.0.3): Extracting archive
  - Installing theseer/tokenizer (1.2.0): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.2): Extracting archive
  - Installing phpunit/php-code-coverage (7.0.14): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (1.12.2): Extracting archive
  - Installing phar-io/version (3.0.4): Extracting archive
  - Installing phar-io/manifest (2.0.1): Extracting archive
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phpunit/phpunit (8.5.13): Extracting archive
  - Installing webmozart/path-util (2.3.0): Extracting archive
  - Installing openlss/lib-array2xml (1.0.0): Extracting archive
  - Installing netresearch/jsonmapper (v2.1.0): Extracting archive
  - Installing felixfbecker/language-server-protocol (v1.5.0): Extracting archive
  - Installing felixfbecker/advanced-json-rpc (v3.1.1): Extracting archive
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Extracting archive
  - Installing amphp/amp (v2.5.1): Extracting archive
  - Installing amphp/byte-stream (v1.8.0): Extracting archive
  - Installing vimeo/psalm (4.3.2): Extracting archive
9 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
46 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../doctrine/coding-standard/lib,../../slevomat/coding-standard
> Koriym\PhpSkeleton\Installer::postInstall
Script Koriym\PhpSkeleton\Installer::postInstall handling the post-create-project-cmd event terminated with an exception

                                                                                                        
  [ErrorException]                                                                                      
  copy(/Users/kenji/tmp/test/tests/SkeletonTest.php): failed to open stream: No such file or directory  
                                                                                                        

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]
```

### PR DESCRIPTION
**Pull request by kenjis**
Fix #61 and so on.

### CODE REVIEW

**Comment by koriym** [comment]
We need to add the file on post process.

**Comment by kenjis** [comment]
What do you mean?

**Comment by koriym** [comment]
1. Rename `.gitattribute` to make it invalid. (like  `.gitattribute.txt`)
2. Recover name from `.gitattribute.txt` to `.gitattribute` on post install script as we do for README (https://github.com/koriym/Koriym.PhpSkeleton/blob/f1683486b4232385bb634a60c1fccac0707e1a69/src/Installer.php#L99)

**Comment by koriym** [comment]
@kenjis I'll take care of this issue. Thank you for taking the time to do this!

**Comment by kenjis** [comment]
Thanks!

**Pull request closed without merging**
